<?php

namespace Database\Seeders;

use App\Models\Surah;
use Illuminate\Database\Seeder;

class SurahSeeder extends Seeder
{
    public function run(): void
    {
        $surahs = [
            [1,'ٱلْفَاتِحَة','Al-Fatihah','Pembukaan',7,1,'makkiyah'],
            [2,'ٱلْبَقَرَة','Al-Baqarah','Sapi Betina',286,1,'madaniyah'],
            [3,'آلِ عِمْرَان','Ali Imran','Keluarga Imran',200,3,'madaniyah'],
            [4,'ٱلنِّسَاء','An-Nisa','Wanita',176,4,'madaniyah'],
            [5,'ٱلْمَائِدَة','Al-Maidah','Hidangan',120,6,'madaniyah'],
            [6,'ٱلْأَنْعَام','Al-Anam','Binatang Ternak',165,7,'makkiyah'],
            [7,'ٱلْأَعْرَاف','Al-Araf','Tempat Tertinggi',206,8,'makkiyah'],
            [8,'ٱلْأَنْفَال','Al-Anfal','Rampasan Perang',75,9,'madaniyah'],
            [9,'ٱلتَّوْبَة','At-Tawbah','Pengampunan',129,10,'madaniyah'],
            [10,'يُونُس','Yunus','Nabi Yunus',109,11,'makkiyah'],
            [11,'هُود','Hud','Nabi Hud',123,11,'makkiyah'],
            [12,'يُوسُف','Yusuf','Nabi Yusuf',111,12,'makkiyah'],
            [13,'ٱلرَّعْد','Ar-Rad','Guruh',43,13,'madaniyah'],
            [14,'إِبْرَاهِيم','Ibrahim','Nabi Ibrahim',52,13,'makkiyah'],
            [15,'ٱلْحِجْر','Al-Hijr','Gunung Batu',99,14,'makkiyah'],
            [16,'ٱلنَّحْل','An-Nahl','Lebah',128,14,'makkiyah'],
            [17,'ٱلْإِسْرَاء','Al-Isra','Perjalanan Malam',111,15,'makkiyah'],
            [18,'ٱلْكَهْف','Al-Kahf','Gua',110,15,'makkiyah'],
            [19,'مَرْيَم','Maryam','Maryam',98,16,'makkiyah'],
            [20,'طه','Taha','Taha',135,16,'makkiyah'],
            [21,'ٱلْأَنْبِيَاء','Al-Anbiya','Para Nabi',112,17,'makkiyah'],
            [22,'ٱلْحَجّ','Al-Hajj','Haji',78,17,'madaniyah'],
            [23,'ٱلْمُؤْمِنُون','Al-Muminun','Orang-orang Beriman',118,18,'makkiyah'],
            [24,'ٱلنُّور','An-Nur','Cahaya',64,18,'madaniyah'],
            [25,'ٱلْفُرْقَان','Al-Furqan','Pembeda',77,18,'makkiyah'],
            [26,'ٱلشُّعَرَاء','Asy-Syuara','Para Penyair',227,19,'makkiyah'],
            [27,'ٱلنَّمْل','An-Naml','Semut',93,19,'makkiyah'],
            [28,'ٱلْقَصَص','Al-Qasas','Kisah-kisah',88,20,'makkiyah'],
            [29,'ٱلْعَنْكَبُوت','Al-Ankabut','Laba-laba',69,20,'makkiyah'],
            [30,'ٱلرُّوم','Ar-Rum','Romawi',60,21,'makkiyah'],
            [31,'لُقْمَان','Luqman','Luqman',34,21,'makkiyah'],
            [32,'ٱلسَّجْدَة','As-Sajdah','Sujud',30,21,'makkiyah'],
            [33,'ٱلْأَحْزَاب','Al-Ahzab','Golongan-golongan',73,21,'madaniyah'],
            [34,'سَبَأ','Saba','Kaum Saba',54,22,'makkiyah'],
            [35,'فَاطِر','Fatir','Pencipta',45,22,'makkiyah'],
            [36,'يس','Yasin','Yasin',83,22,'makkiyah'],
            [37,'ٱلصَّافَّات','As-Saffat','Yang Bershaf-shaf',182,23,'makkiyah'],
            [38,'ص','Sad','Sad',88,23,'makkiyah'],
            [39,'ٱلزُّمَر','Az-Zumar','Rombongan-rombongan',75,23,'makkiyah'],
            [40,'غَافِر','Gafir','Yang Maha Pengampun',85,24,'makkiyah'],
            [41,'فُصِّلَت','Fussilat','Yang Dijelaskan',54,24,'makkiyah'],
            [42,'ٱلشُّورَى','Asy-Syura','Musyawarah',53,25,'makkiyah'],
            [43,'ٱلْزُّخْرُف','Az-Zukhruf','Perhiasan',89,25,'makkiyah'],
            [44,'ٱلدُّخَان','Ad-Dukhan','Asap',59,25,'makkiyah'],
            [45,'ٱلْجَاثِيَة','Al-Jasiyah','Yang Berlutut',37,25,'makkiyah'],
            [46,'ٱلْأَحْقَاف','Al-Ahqaf','Bukit-bukit Pasir',35,26,'makkiyah'],
            [47,'مُحَمَّد','Muhammad','Muhammad',38,26,'madaniyah'],
            [48,'ٱلْفَتْح','Al-Fath','Kemenangan',29,26,'madaniyah'],
            [49,'ٱلْحُجُرَات','Al-Hujurat','Kamar-kamar',18,26,'madaniyah'],
            [50,'ق','Qaf','Qaf',45,26,'makkiyah'],
            [51,'ٱلذَّارِيَات','Az-Zariyat','Angin yang Menerbangkan',60,26,'makkiyah'],
            [52,'ٱلطُّور','At-Tur','Bukit',49,27,'makkiyah'],
            [53,'ٱلنَّجْم','An-Najm','Bintang',62,27,'makkiyah'],
            [54,'ٱلْقَمَر','Al-Qamar','Bulan',55,27,'makkiyah'],
            [55,'ٱلرَّحْمَٰن','Ar-Rahman','Yang Maha Pemurah',78,27,'madaniyah'],
            [56,'ٱلْوَاقِعَة','Al-Waqiah','Hari Kiamat',96,27,'makkiyah'],
            [57,'ٱلْحَدِيد','Al-Hadid','Besi',29,27,'madaniyah'],
            [58,'ٱلْمُجَادِلَة','Al-Mujadilah','Wanita yang Gugat',22,28,'madaniyah'],
            [59,'ٱلْحَشْر','Al-Hasyr','Pengusiran',24,28,'madaniyah'],
            [60,'ٱلْمُمْتَحَنَة','Al-Mumtahanah','Wanita yang Diuji',13,28,'madaniyah'],
            [61,'ٱلصَّفّ','As-Saf','Barisan',14,28,'madaniyah'],
            [62,'ٱلْجُمُعَة','Al-Jumuah','Hari Jumat',11,28,'madaniyah'],
            [63,'ٱلْمُنَافِقُون','Al-Munafiqun','Orang-orang Munafik',11,28,'madaniyah'],
            [64,'ٱلتَّغَابُن','At-Tagabun','Pengungkapan Kesalahan',18,28,'madaniyah'],
            [65,'ٱلطَّلَاق','At-Talaq','Talak',12,28,'madaniyah'],
            [66,'ٱلتَّحْرِيم','At-Tahrim','Pengharaman',12,28,'madaniyah'],
            [67,'ٱلْمُلْك','Al-Mulk','Kerajaan',30,29,'makkiyah'],
            [68,'ٱلْقَلَم','Al-Qalam','Pena',52,29,'makkiyah'],
            [69,'ٱلْحَاقَّة','Al-Haqqah','Hari Kiamat',52,29,'makkiyah'],
            [70,'ٱلْمَعَارِج','Al-Maarij','Tempat-tempat Naik',44,29,'makkiyah'],
            [71,'نُوح','Nuh','Nabi Nuh',28,29,'makkiyah'],
            [72,'ٱلْجِنّ','Al-Jinn','Jin',28,29,'makkiyah'],
            [73,'ٱلْمُزَّمِّل','Al-Muzzammil','Orang yang Berselimut',20,29,'makkiyah'],
            [74,'ٱلْمُدَّثِّر','Al-Muddassir','Orang Berselimut',56,29,'makkiyah'],
            [75,'ٱلْقِيَامَة','Al-Qiyamah','Hari Kiamat',40,29,'makkiyah'],
            [76,'ٱلْإِنسَان','Al-Insan','Manusia',31,29,'madaniyah'],
            [77,'ٱلْمُرْسَلَات','Al-Mursalat','Malaikat-malaikat yang Diutus',50,29,'makkiyah'],
            [78,'ٱلنَّبَأ','An-Naba','Berita Besar',40,30,'makkiyah'],
            [79,'ٱلنَّازِعَات','An-Naziat','Malaikat-malaikat yang Mencabut',46,30,'makkiyah'],
            [80,'عَبَسَ','Abasa','Ia Bermuka Masam',42,30,'makkiyah'],
            [81,'ٱلتَّكْوِير','At-Takwir','Penggulungan',29,30,'makkiyah'],
            [82,'ٱلْإِنفِطَار','Al-Infitar','Terbelah',19,30,'makkiyah'],
            [83,'ٱلْمُطَفِّفِين','Al-Mutaffifin','Orang-orang yang Curang',36,30,'makkiyah'],
            [84,'ٱلْإِنشِقَاق','Al-Insyiqaq','Terbelah',25,30,'makkiyah'],
            [85,'ٱلْبُرُوج','Al-Buruj','Gugusan Bintang',22,30,'makkiyah'],
            [86,'ٱلطَّارِق','At-Tariq','Yang Datang di Malam Hari',17,30,'makkiyah'],
            [87,'ٱلْأَعْلَى','Al-Ala','Yang Paling Tinggi',19,30,'makkiyah'],
            [88,'ٱلْغَاشِيَة','Al-Gasiyah','Hari Pembalasan',26,30,'makkiyah'],
            [89,'ٱلْفَجْر','Al-Fajr','Fajar',30,30,'makkiyah'],
            [90,'ٱلْبَلَد','Al-Balad','Negeri',20,30,'makkiyah'],
            [91,'ٱلشَّمْس','Asy-Syams','Matahari',15,30,'makkiyah'],
            [92,'ٱللَّيْل','Al-Lail','Malam',21,30,'makkiyah'],
            [93,'ٱلضُّحَىٰ','Ad-Duha','Waktu Dhuha',11,30,'makkiyah'],
            [94,'ٱلشَّرْح','Asy-Syarh','Kelapangan',8,30,'makkiyah'],
            [95,'ٱلتِّين','At-Tin','Buah Tin',8,30,'makkiyah'],
            [96,'ٱلْعَلَق','Al-Alaq','Segumpal Darah',19,30,'makkiyah'],
            [97,'ٱلْقَدْر','Al-Qadr','Kemuliaan',5,30,'makkiyah'],
            [98,'ٱلْبَيِّنَة','Al-Bayyinah','Bukti yang Nyata',8,30,'madaniyah'],
            [99,'ٱلزَّلْزَلَة','Az-Zalzalah','Gempa Bumi',8,30,'madaniyah'],
            [100,'ٱلْعَادِيَات','Al-Adiyat','Kuda yang Berlari Kencang',11,30,'makkiyah'],
            [101,'ٱلْقَارِعَة','Al-Qariah','Hari Kiamat',11,30,'makkiyah'],
            [102,'ٱلتَّكَاثُر','At-Takasur','Bermegah-megahan',8,30,'makkiyah'],
            [103,'ٱلْعَصْر','Al-Asr','Masa',3,30,'makkiyah'],
            [104,'ٱلْهُمَزَة','Al-Humazah','Pengumpat',9,30,'makkiyah'],
            [105,'ٱلْفِيل','Al-Fil','Gajah',5,30,'makkiyah'],
            [106,'قُرَيْش','Quraisy','Suku Quraisy',4,30,'makkiyah'],
            [107,'ٱلْمَاعُون','Al-Maun','Barang-barang yang Berguna',7,30,'makkiyah'],
            [108,'ٱلْكَوْثَر','Al-Kausar','Nikmat yang Banyak',3,30,'makkiyah'],
            [109,'ٱلْكَافِرُون','Al-Kafirun','Orang-orang Kafir',6,30,'makkiyah'],
            [110,'ٱلنَّصْر','An-Nasr','Pertolongan',3,30,'madaniyah'],
            [111,'ٱلْمَسَد','Al-Masad','Gejolak Api',5,30,'makkiyah'],
            [112,'ٱلْإِخْلَاص','Al-Ikhlas','Ikhlas',4,30,'makkiyah'],
            [113,'ٱلْفَلَق','Al-Falaq','Waktu Subuh',5,30,'makkiyah'],
            [114,'ٱلنَّاس','An-Nas','Manusia',6,30,'makkiyah'],
        ];

        foreach ($surahs as [$nomor, $arab, $latin, $indo, $ayat, $juz, $tempat]) {
            Surah::updateOrCreate(
                ['nomor' => $nomor],
                [
                    'nama_arab'      => $arab,
                    'nama_latin'     => $latin,
                    'nama_indonesia' => $indo,
                    'jumlah_ayat'    => $ayat,
                    'juz'            => $juz,
                    'tempat_turun'   => $tempat,
                ]
            );
        }
    }
}
